### ISSUE TITLE
Remplacer pdal info par quickinfo pour éviter d'utiliser subprocess

### ISSUE THREAD

**Issue by CharlesGaydon** [IGNF/ign-pdal-tools#25]
https://github.com/IGNF/ign-pdal-tools/blob/bf997a7d3f40b79d8c348c3e36ac4fb5fd53eb7a/pdaltools/color.py#L106

**Comment by leavauchier** [comment]
Devrait être corrigé par https://github.com/IGNF/ign-pdal-tools/pull/37. 
A réouvrir si des problèmes persistent
